FROM registry.fedoraproject.org/fedora:31

ENV VEC_HOME=/home/vectext

WORKDIR $VEC_HOME

RUN dnf -y update && \
    dnf install -y --setopt=tsflags=nodocs \
        bzip2 \
        dbus-glib \
        dejavu-sans-fonts \
        dejavu-serif-fonts \
        dumb-init \
        fluxbox \
        libappindicator-gtk3 \
        libcurl \
        liberation-fonts \
        libXScrnSaver \
        net-tools \
        redhat-lsb \
        tigervnc-server \
        unzip \
        wget \
        xdg-utils \
        xdotool && \
    dnf clean all && \
    touch $VEC_HOME/.Xauthority && \
    mkdir -p $VEC_HOME/.cache/dconf && \
    mkdir -p $VEC_HOME/.mozilla/plugins

ENV VNC_PORT=5999 \
    DISPLAY=:99 \
    HOME=$VEC_HOME

# vnc port
EXPOSE $VNC_PORT

COPY ./xstartup ./config .vnc/


RUN chmod a+x $VEC_HOME/.vnc/xstartup && \
    chgrp -R 0 $VEC_HOME && \
    chmod -R g=u $VEC_HOME

# VecText specific

RUN dnf install perl libX11-devel -y

RUN dnf install zlib-devel libpng libpng-devel -y

RUN [ "cpan", "install", "YAML"]

RUN dnf install perl-* -y

RUN [ "cpan", "install", "Tk"]
RUN [ "cpan", "install", "Tk::FileDialog"]
RUN [ "cpan", "install", "Tk::DirSelect"]
RUN [ "cpan", "install", "-T", "Tk::Help"]
# RUN [ "cpan", "install", "Win32"]
# RUN [ "cpan", "install", "Win32::LongPath"]
RUN [ "cpan", "install",  "List::Util"]
RUN [ "cpan", "install",  "Cwd"]
RUN [ "cpan", "install",  "URI::Find"]
RUN [ "cpan", "install",  "Lingua::Stem::Snowball"]
RUN [ "cpan", "install",  "Encode::Unicode"]
COPY ./VecText /usr/src/VecText

# Patch the script
WORKDIR /usr/local/lib/perl5/site_perl/5.30.2/Tk/
COPY ./FileDialog.patched /
RUN diff -u FileDialog.pm /FileDialog.patched > /FileDialog.patch  || echo "Patch generated"
RUN patch --verbose -p0 --fuzz=0 < /FileDialog.patch
RUN cat /usr/local/lib/perl5/site_perl/5.30.2/Tk/FileDialog.pm | grep '\^W'

WORKDIR /usr/src/VecText

USER 1001

ENTRYPOINT /usr/bin/dumb-init vncserver $DISPLAY -fg -Log *:stderr:100

# CMD [ "perl", "./vectext-cmdline.pl" ]
